version: "3"
services:
  nginx:
    image: nginx:stable
    container_name: lpa_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9001:80
    depends_on:
      - backend
      - frontend

  backend:
    image: linkedpipes/applications:backend
    container_name: lpa_backend
    volumes:
      - "./config.properties:/app/config.properties"

  frontend:
    image: linkedpipes/applications:frontend
    container_name: lpa_frontend

  db:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    volumes:
      - ./data/virtuoso:/data

  # Discovery service runs locally in port 9000
  discovery:
    image: linkedpipes/discovery
    container_name: lpa_discovery
    stdin_open: true