version: "3"
services:
  nginx:
    image: nginx:stable
    container_name: lpa_reverse_proxy
    volumes:
      - ./nginx-prod.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  backend:
    image: linkedpipes/applications:backend
    container_name: lpa_backend
    volumes:
      - "./config.properties:/app/config.properties"
    depends_on:
      - etl
      - discovery

  frontend:
    image: linkedpipes/applications:frontend-prod
    container_name: lpa_frontend
    depends_on:
      - backend

  db:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    volumes:
      - ./data/virtuoso:/data

  discovery:
    image: linkedpipes/applications:discovery
    container_name: lpa_discovery
    command:
      [
        "40",
        "-Dldcp.etl.hostname=http://lpa_etl:8080",
        "-Dplay.http.secret.key=yourRandomSecret",
        "-Dpidfile.path=/dev/null",
      ]
    depends_on:
      - db
      - etl
  
  etl:
    image: linkedpipes/etl
    container_name: lpa_etl
    ports:
      - 8080:8080