version: "3.3"
services:
  nginx:
    image: nginx:stable
    container_name: lpa-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9001:80"
    restart: on-failure
    depends_on:
      - backend
      - frontend

  backend:
    image: linkedpipes/applications:backend
    container_name: lpa-backend
    environment:
      SENTRY_ENVIRONMENT: "development"
    build:
      context: src/backend/
    ports:
      - "9005:9005"
      - "9092:9092"
    restart: on-failure
    depends_on:
      - etl
      - discovery
      - flyway

  frontend:
    image: linkedpipes/applications:frontend
    container_name: lpa-frontend
    build:
      context: src/frontend/
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - backend

  # Refer to http://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFPerformanceTuning
  # For adjusting the NumberOfButters and MaxDirtyBuffers according to your RAM size
  db:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    container_name: lpa-virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
      VIRT_SPARQL_ResultSetMaxRows: 1000000
      VIRT_Parameters_NumberOfBuffers: 170000
      VIRT_Parameters_MaxDirtyBuffers: 130000
      VIRT_Parameters_ThreadCleanupInterval: 1
      VIRT_Parameters_ResourcesCleanupInterval: 1
      VIRT_Parameters_MaxCheckpointRemap: 3750
      VIRT_Parameters_CheckpointInterval: 1
    ports:
      - "8890:8890"
    restart: on-failure
    volumes:
      - ./data/virtuoso:/var/lib/virtuoso/data

  discovery:
    image: linkedpipes/applications:discovery
    container_name: lpa-discovery
    command:
      [
        "0",
        "-Dldcp.etl.hostname=http://lpa-etl:8080",
        "-Dplay.http.secret.key=yourRandomSecret",
        "-Dpidfile.path=/dev/null",
      ]
    depends_on:
      - db
      - etl
    restart: on-failure
    ports:
      - "9000:9000"

  etl:
    image: linkedpipes/applications:etl_devel
    container_name: lpa-etl
    restart: on-failure
    ports:
      - "8080:8080"

  postgres:
    image: postgres:10.7
    container_name: lpa-postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: lpa
      PGDATA: /tmp
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flyway:
    image: boxfuse/flyway
    command: -url=jdbc:postgresql://lpa-postgres:5432/lpa -user=lpa -password=example -connectRetries=60 migrate
    volumes:
      - ./src/backend/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
